### ISSUE TITLE
Error after install

### ISSUE THREAD

**Issue by yaroslavvoloshchuk-codaio** [gobezu/k2fields#33] opened 2012-04-10 22:20 UTC
Sorry for my bad english ;(
I have installed Joomla 2.5.4 .
Main page have drop fatal error when k2-k2 fields plugin was enabled. All plugins requirements, that were in install guide, are made.

Fatal error: Cannot redeclare class K2HelperRoute in /home/ksc/ksc.kiev.ua/new/components/com_k2/helpers/route.php on line 16

**Comment by gobezu** [comment] 2012-04-11 01:44
No worries about bad English.
It is indeed difficult to figure out what could be the cause on the basis of provided info and if possible I would like to take a closer look at the site.
So please do use http://jproven.com/k2fields/contact to contact me with your details.

**Comment by gobezu** [comment] 2012-04-11 17:05
Various commits done related to this issue which is all thanks to extensions not using Joomla API to load there various libraries and models rather resort to simple PHP require or include, wrecking havoc in efforts to override.

Most of these were addressed in earlier commits and one remains, but can consider this effort to be through in this round.

**Closed as completed by gobezu** 2012-04-11 17:05 UTC
Labels: investigate
